server:
  port: 8081
  servlet:
    context-path: /test

spring:
  application:
    name: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: lore
    driver-class-name: org.postgresql.Driver
    #hikari:
      #schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

